name: Comment On PR With Build URL
on:
  workflow_run:
    workflows: ['Slash Command Build']
    types: [completed]
jobs:
  commentOnPrWithBuildUrl:
    if: github.event.workflow_run.event == 'repository_dispatch' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch artifacts
        id: fetch_artifacts
        run: |
          artifact_id=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}/artifacts | jq .artifacts[0].id)
          echo "::set-output name=artifact_id::${artifact_id}"

      - name: Get artifact ID
        run: |
          echo "${{steps.fetch_artifacts.outputs.artifact_id}}"
