name: Comment On PR With Build URL
on:
  workflow_run:
    workflows: ['Slash Command Build']
    types: [completed]
jobs:
  commentOnPrWithBuildUrl:
    # if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      # - name: Get artifact ID
      #   run: |
      #     artifacts=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts)

      #     echo "$artifacts"


      - name: Get workflow event
        run: |
          echo "${{github.event.workflow_run.event}}"
