name: Comment On PR With Build URL
on:
  workflow_run:
    workflows: ['Slash Command Build']
    types: [completed]
jobs:
  commentOnPrWithBuildUrl:
    if: github.event.workflow_run.event == 'repository_dispatch' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch artifacts
        id: fetch_artifacts
        run: |
          artifact=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}/artifacts | jq .artifacts[0])
          artifact_id=$(jq -r '.id' <<< "${artifact}")
          artifact_name=$(jq -r '.name' <<< "${artifact}")
          issue_id=${artifact_name##*-}
          echo "::set-output name=artifact_id::${artifact_id}"
          echo "::set-output name=issue_id::${issue_id}"

      - name: Get details
        run: |
          echo "${{steps.fetch_artifacts.outputs.artifact_id}}"
          echo "${{steps.fetch_artifacts.outputs.issue_id}}"
